/*
 * File: remote_client.c
 * Purpose: RPC client that requests logged-in user information
 * 
 * Compilation:
 * gcc -o remote_client remote_client.c remote_clnt.c remote_xdr.c -lnsl
 * 
 * Usage:
 * ./remote_client <hostname> [1|2]
 * hostname: Server hostname or IP address
 * 1: Get structured user list (default)
 * 2: Get formatted string output
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <rpc/rpc.h>
#include "remote.h"  /* Generated by rpcgen */

void display_structured_users(CLIENT *clnt) {
    user_list *result;
    int i;
    
    printf("\nCalling remote procedure: GET_LOGGED_USERS\n");
    printf("==================================================\n");
    
    /* Call remote procedure */
    result = get_logged_users_1(NULL, clnt);
    
    if (result == NULL) {
        clnt_perror(clnt, "Call failed");
        return;
    }
    
    printf("Received information for %d user(s):\n\n", result->count);
    printf("%-10s %-10s %-16s %s\n", "USER", "TTY", "FROM", "LOGIN@");
    printf("================================================================\n");
    
    /* Display each user */
    for (i = 0; i < result->count; i++) {
        printf("%-10s %-10s %-16s %s\n",
               result->users.users_val[i].username,
               result->users.users_val[i].terminal,
               result->users.users_val[i].hostname,
               result->users.users_val[i].logintime);
    }
}

void display_string_users(CLIENT *clnt) {
    char **result;
    
    printf("\nCalling remote procedure: GET_USERS_STRING\n");
    printf("==================================================\n");
    
    /* Call remote procedure */
    result = get_users_string_1(NULL, clnt);
    
    if (result == NULL) {
        clnt_perror(clnt, "Call failed");
        return;
    }
    
    printf("\n%s\n", *result);
}

int main(int argc, char *argv[]) {
    CLIENT *clnt;
    char *host;
    int choice = 1;
    
    /* Check command line arguments */
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <hostname> [1|2]\n", argv[0]);
        fprintf(stderr, "  1: Get structured user list (default)\n");
        fprintf(stderr, "  2: Get formatted string output\n");
        exit(EXIT_FAILURE);
    }
    
    host = argv[1];
    
    if (argc >= 3) {
        choice = atoi(argv[2]);
        if (choice < 1 || choice > 2) {
            fprintf(stderr, "Invalid choice. Using default (1)\n");
            choice = 1;
        }
    }
    
    printf("Connecting to RPC server on host: %s\n", host);
    
    /*
     * Create client handle
     * clnt_create() parameters:
     * 1. hostname: Server host
     * 2. program number: REMOTE_PROG (from remote.h)
     * 3. version number: REMOTE_VERS (from remote.h)
     * 4. protocol: "udp" or "tcp"
     */
    clnt = clnt_create(host, REMOTE_PROG, REMOTE_VERS, "udp");
    
    if (clnt == NULL) {
        /* 
         * clnt_pcreateerror() prints error message 
         * explaining why clnt_create() failed
         */
        clnt_pcreateerror(host);
        exit(EXIT_FAILURE);
    }
    
    printf("Successfully connected to server\n");
    
    /* Call appropriate remote procedure */
    switch (choice) {
        case 1:
            display_structured_users(clnt);
            break;
        case 2:
            display_string_users(clnt);
            break;
    }
    
    /*
     * Destroy client handle and free resources
     */
    clnt_destroy(clnt);
    
    printf("\nClient finished successfully\n");
    
    return 0;
}

/*
 * DETAILED EXPLANATION OF RPC FUNCTIONS:
 * 
 * 1. clnt_create():
 *    - Creates CLIENT handle for RPC communication
 *    - Establishes connection to RPC server
 *    - Returns NULL on failure
 *    - Syntax: CLIENT *clnt_create(char *host, u_long prog, 
 *                                   u_long vers, char *proto)
 * 
 * 2. clnt_pcreateerror():
 *    - Prints error message when clnt_create() fails
 *    - Includes reason for failure (e.g., server not running)
 *    - Syntax: void clnt_pcreateerror(char *msg)
 * 
 * 3. clnt_perror():
 *    - Prints error message for RPC call failures
 *    - Used when remote procedure call returns NULL
 *    - Syntax: void clnt_perror(CLIENT *clnt, char *msg)
 * 
 * 4. clnt_destroy():
 *    - Destroys CLIENT handle
 *    - Frees all associated resources
 *    - Must be called before program exits
 *    - Syntax: void clnt_destroy(CLIENT *clnt)
 * 
 * 5. Remote procedure calls:
 *    - Format: <procedure_name>_<version>(args, CLIENT *clnt)
 *    - Generated by rpcgen from remote.x
 *    - Returns pointer to result or NULL on error
 *    - Result memory managed by RPC library
 */